sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: 0HKYJYYvnFOeuXLuy28cz20Humht7OOz+uWuddsMIlkSJM3YNR01Wwl50KleAsbmP6j1Ce7L7mYHk0YsQlehqP2+4V63UGHTC9jx6vvHutQi7TEZpH4FHlArkgwiA1wxFSCs7E2YeT9CZn03UlgFceyrFO3LEWJdMVqyTkjfRNEw8ZVgiRb8t5rJucB9t1ZWQKHqHfueAJzD4buT3zvh6M2I5xw2OHAtmrCUlybf0LgjZyEPhhL9H7GENUswoIDrwxFUHTxeEYs2Jqtlcs7hsrwZKqZMNeXoEpZu6ICV+cgCCcz1QydQL32gMLeCKMIIIQNB9uoARpB9zM/a+Ymc3XbDOEjPwyUpy6rXb36JQXJm4Kbe3jJnr8/h4Ao1w7eEnTxvaphBLxalAJtd58ErEP4LBDazWgHau6wL4QVJvOA9oB21Z0zaGUqI1zJspodsZcmK7m6k1F2c2oHWfCoDTFv1lIWhFIVNSZrwnA3Kt7g+t/DPihgQqOyweVzBkn9nTXrLRz98MdEy+X3jYI5osZ37BY5n4Ru14f7z8KMmlp7C5xQqhKPJnpDmsBBCa313Vty0U7ydGgeHXkxYpZDPIyptbd5fiqGrOQplvCTVmChPBZ7KrAMmhIB6jTAPH1lSj6+Xi4Yq3uDqaOfypnwP45JQ4WbrQze5T4fB4pEVLXk=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Maid-of-Maiden-Lane_5757
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy